# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "blue-velvet_left", "blue-velvet_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41

---
include:
  - board: ergohaven
    shield: velvet_v3_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: velvet_v3_ruen velvet_v3_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_right

  - board: ergohaven
    shield: velvet_v3_ui_left
  - board: ergohaven
    shield: velvet_v3_ui_ruen velvet_v3_ui_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: velvet_v3_ui_right_ruen-ergohaven-zmk
  - board: ergohaven
    shield: velvet_v3_ui_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: ergohaven
    shield: op36_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: op36_ruen op36_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: op36_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: op36_right

  - board: ergohaven
    shield: settings_reset
